### PR TITLE
Updated Translation Pt-Br

### PR DESCRIPTION
**Pull request by gersonvagner**
Be patient with me! I'm starting now with all this! :)

### CODE REVIEW

**Comment by downpoured** [comment]
Hi, thank you for the contribution! I think you are the first to contribute strings for version 4.

Do you think you could also add the new strings from versions 3.0.0 to 3.3.5? You can see these in
http://www.scintilla.org/locale.properties

Also, it looks like you have changed the alt-hotkeys (&) for many of the menus. Was there a problem with the way they were previously?

-Ben

**Comment by gersonvagner** [comment]
Oh, sorry! Im said was me a newbie! Im tested some things here and bring the file without give back the hotkeys. I'll update this right now! By the way, about the 3.0.0 to 3.3.5 versions, I'll do this whit pleasure, and delivery soon! :)

**Comment by gersonvagner** [comment]
Maybe is ready now. If you will can analyze this, I will apreciated. I placed the hotkeys in his place and did the translation for 3.0.0 to 3.3.5 versions, how you requested. Please check if I did this right! Im glad for help. ;)

**Comment by downpoured** [comment]
Thank you for contributing!

I re-ordered the items so that it was in the same order as
https://raw.githubusercontent.com/downpoured/scite-files/master/files/files/translations/locale.en.properties
but aside from that, everything is good!

**Pull request merged**
